version: '2'
services:
    bikefriends-app:
        image: bikefriends
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bikefriends-mysql:3306/bikefriends?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bikefriends-mysql:
        extends:
            file: mysql.yml
            service: bikefriends-mysql
